[build]
  command = "pnpm run build"
  publish = ".netlify/dist"

[build.environment]
  NODE_OPTIONS = "--max-old-space-size=4096"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200